Use customer_shopping_behavior_AmlanMohantyYT;
SELECT * FROM customer_shopping_behavior_AmlanMohantyYT.Customer_behaviour;
-- Q1. What is the total revenue generated by male vs. female customers?
select gender,SUM(purchase_amount) as revenue
from Customer_behaviour group by gender;


-- Q2. Which customers used a discount but still spent more than the average purchase amount?
select customer_id, purchase_amount 
from Customer_behaviour 
where discount_applied='Yes' and purchase_amount>=(select avg(purchase_amount)from Customer_behaviour)


-- Q3. Which are the top 5 products with the highest average review rating?
select item_purchased, round(avg(review_rating),2) as 'avg_rating' from Customer_behaviour
group by item_purchased order by 'avg_rating' desc
limit 5


-- Q4. Compare the average Purchase Amounts between Standard and Express Shipping.
select shipping_type, avg(purchase_amount) from Customer_behaviour where shipping_type in('Standard','Express')
group by shipping_type;
-- :- Average purchase amount is more by 2.1% in case express shipping


-- Q5. Do subscribed customers spend more? Compare average spend and total revenue between subscribers and non-subscribers.
select subscription_status,
count(customer_id)as total_customers,
Avg(purchase_amount) as avg_spend,
sum(purchase_amount) as total_spend
from Customer_behaviour
group by subscription_status order by avg_spend, total_spend desc;
-- Total spend in case of subscribed customers is more than the unsubscribd customers yet the average spend of both customers are same
	

-- Q6. Which 5 products have the highest percentage of purchases with discounts applied?
select item_purchased,round(100*sum(case when discount_applied='Yes' Then 1 Else 0 End)/count(*),2)as discount_rate
from Customer_behaviour
group by item_purchased
order by discount_rate desc
limit 5;
-- with the use of case function i was able to validate the items where discount was applied and get the percentage grouped by top 5 items


-- Q7. Segment customers into New, Returning, and Loyal based on their total number of previous purchases, and show the count of each segment.
with customer_type as
	(select customer_id, previous_purchases,
    case
		when previous_purchases=1 then 'New'
        when previous_purchases between 2 and 10 then 'Returning'
        else 'Loyal' end as customer_segment
	from Customer_behaviour)
Select customer_segment, count(*) as Number_of_customers
from customer_type
group by customer_segment;
-- customer segmentation performed by the number of times the customer purchased the items


-- Q8. What are the top 3 most purchased products within each category?
with item_counts as (
select category,
item_purchased,
count(customer_id) as total_orders,
row_number() over(partition by category order by count(customer_id)desc) as item_rank
from Customer_behaviour
group by category, item_purchased)
select item_rank, category, item_purchased, total_orders 
from item_counts where item_rank>=3;


-- Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
select subscription_status,
count(customer_id) as repeat_buyers from Customer_behaviour
where previous_purchases>5
group by subscription_status


-- Q10. What is the revenue contribution of each age group?
select age_group,
SUM(purchase_amount) as Revenue from Customer_behaviour
group by age_group
order by Revenue desc;